version: '3.5'
services:
  zabbix-pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: zabbix_db
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    ports:
      - "10051:10051"
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: zabbix
    depends_on:
      - "zabbix-pgsql"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "America/Porto_Velho"
    depends_on:
      - "zabbix-pgsql"
      - "zabbix-server"
    ports:
      - "80:8080"

  zabbix-agent:
    image: zabbix/zabbix-agent
    ports:
      - "10050:10050"
    restart: always
    depends_on:
      - "zabbix-pgsql"
      - "zabbix-server"
    environment:
      ZBX_HOSTNAME: zabbix-agent

  grafana:
    image: grafana/grafana:latest
    user: 'root'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
      - grafana-config:/etc/grafana:rw
      - grafana-data:/var/lib/grafana:rw
      - grafana-home:/usr/share/grafana:rw
    ports:
      - '3000:3000'
    depends_on:
      - "zabbix-server"

  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
  grafana-config:
  grafana-data:
  grafana-home:
