version: '3.5'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.vars.md

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    ports:
      - "10051:10051"
    restart: always
    depends_on:
      - "db"
    env_file:
      - ./.vars.md

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    ports:
      - "80:80"
    restart: always
    depends_on:
      - "db"
      - "zabbix-server"
    environment:
      ZBX_SERVER_HOST: zabbix-server
    env_file:
      - ./.vars.md

  zabbix-agent:
    image: zabbix/zabbix-agent
    ports:
      - "10050:10050"
    restart: always
    depends_on:
      - "db"
      - "zabbix-server"
    environment:
      ZBX_HOSTNAME: zabbix-agent

  grafana:
    image: grafana/grafana:latest
    user: 'root'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
      - grafana-config:/etc/grafana:rw
      - grafana-data:/var/lib/grafana:rw
      - grafana-home:/usr/share/grafana:rw
    ports:
      - '3000:3000'
    depends_on:
      - "zabbix-server"

  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
  grafana-config:
  grafana-data:
  grafana-home:
