version: '3.5'
services:
  postgres-server:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.vars.env
  
  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    restart: always
    ports:
      - '10051:10051'
    depends_on:
      - postgres-server
    env_file:
      - ./.vars.env

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
    volumes:
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    ports:
      - '80:80'
    depends_on:
      - postgres-server
      - zabbix-server
    env_file:
      - ./.vars.env
  
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    profiles:
      - full
      - all
    restart: always
    ports:
      - '10050:10050'
    environment:
      ZBX_HOSTNAME: zabbix-agent
    depends_on:
      - postgres-server
      - zabbix-server
    

  grafana:
    image: grafana/grafana:latest
    user: 'root'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
      - grafana-config:/etc/grafana:rw
      - grafana-data:/var/lib/grafana:rw
      - grafana-home:/usr/share/grafana:rw
    ports:
      - '3000:3000'
    depends_on:
      - zabbix-server

volumes:
  pgdata:
  grafana-config:
  grafana-data:
  grafana-home:
