version: '3.5'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.vars.env
  
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-6.0-latest
    container_name: zabbix-server-pgsql
    ports:
      - "10051:10051"
    restart: always
    depends_on:
      - "db"
    env_file:
      - ./.vars.env

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.0-latest
    container_name: zabbix-web-nginx-pgsql
    ports:
      - "80:80"
      - "443:8443"
    restart: always
    depends_on:
      - "db"
      - "zabbix-server"
    environment:
      ZBX_SERVER_HOST: zabbix-server
    env_file:
      - ./.vars.env
  
  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-6.0-latest
    container_name: zabbix-agent
    profiles:
      - full
      - all
    ports:
      - "10050:10050"
    restart: always
    depends_on:
      - "db"
      - "zabbix-server"
    environment:
      ZBX_HOSTNAME: zabbix-agent

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - "6379:6379"

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    ports:
    - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - "redis"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: 'root'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
      - grafana-config:/etc/grafana:rw
      - grafana-data:/var/lib/grafana:rw
      - grafana-home:/usr/share/grafana:rw
    ports:
      - '3000:3000'
    depends_on:
      - "cadvisor"
      - "zabbix-server"

volumes:
  pgdata:
  grafana-config:
  grafana-data:
  grafana-home:
