version: '3.5'
services:
  zabbix-pgsq:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: suasenha
      POSTGRES_DB: zabbix
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    restart: always
    environment:
      DB_SERVER_HOST: "zabbix-pgsq"
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: suasenha
    ports:
      - '10051:10051'
    links:
      - zabbix-pgsq
    depends_on:
      - zabbix-pgsq

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    restart: always
    environment:
      DB_SERVER_HOST: "zabbix-pgsq"
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: suasenha
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "America/Porto_Velho"
    ports:
      - '80:8080'
    links:
      - zabbix-pgsq
      - zabbix-server
    depends_on:
      - zabbix-pgsq
      - zabbix-server
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
      - /var/lib/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs:ro
      - /var/lib/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys:ro

  zabbix-agent:
    image: zabbix/zabbix-agent
    restart: unless-stopped
    environment:
      ZBX_HOSTNAME: zabbix-agent
    ports:
      - '10050:10050'
    links:
      - zabbix-pgsq
      - zabbix-server
    depends_on:
      - zabbix-pgsq
      - zabbix-server

  grafana:
    image: grafana/grafana:latest
    user: 'root'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
      - grafana-config:/etc/grafana:rw
      - grafana-data:/var/lib/grafana:rw
      - grafana-home:/usr/share/grafana:rw
    ports:
      - '3000:3000'
    links:
      - zabbix-pgsq
      - zabbix-server
    depends_on:
      - zabbix-pgsq
      - zabbix-server

  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  grafana-config:
  grafana-data:
  grafana-home:
